from Content.Front_End.Widgets.MenuBar import MenuBar
from Content.Front_End.Widgets.SystemBar import SystemBar
from PyQt5.QtWidgets import QWidget, QGridLayout, QGroupBox, QPushButton, QLabel


class CrawlerWindow(QWidget):

    # Window generated by a SystemBar to help the user
    def __init__(self,parent=None):
        super(CrawlerWindow,self).__init__(parent=parent)

        self.systemBar = SystemBar(parent=self)
        self.menuBar = MenuBar(parent=self)
        self.monitoringMenu = QGroupBox(self)
        self.monitoringMenuLayout = QGridLayout()
        self.monitoringMenu.setLayout(self.monitoringMenuLayout)
        self.monitoringMenu.setGeometry(180, 35, 1100, 690)
        
        self.monitoringMenu.setStyleSheet(
            "QGroupBox {border:3px solid black;background-color:rgba(0,0,0,0.6)}")

        self.initUIContent()
        self.show()

        self.setStyleSheet("QLabel{color:white;background-color:rgba(0,0,0,0)} QPushButton{color:white;background-color:rgba(0,0,0,0)}")

    def initUIContent(self):
        
        self.currentRacesFound = QLabel("Courses Trouvées :")
        self.currentRacesFetched = QLabel("Courses Rappatriées :")

        self.monitoringMenuLayout.addWidget(self.currentRacesFound,0,0,1,1)
        self.monitoringMenuLayout.addWidget(self.currentRacesFetched,0,1,1,1)

        self.finderButton = QPushButton("Lancer la recherche des courses possibles")
        self.finderButton.clicked.connect(
           lambda: self.startCrawling())
        self.monitoringMenuLayout.addWidget(self.finderButton,1,0,1,1)

        self.recupButton = QPushButton("Lancer la récupération des courses recherchées")
        self.recupButton.clicked.connect(
           lambda: self.startCrawling())
        self.monitoringMenuLayout.addWidget(self.recupButton,1,1,1,1)



    def startCrawling(self):
        pass