from Content.Front_End.Widgets.MenuBar import MenuBar
from Content.Front_End.Widgets.SystemBar import SystemBar
from PySide2.QtWidgets import QWidget, QGridLayout, QGroupBox, QPushButton, QLabel


class DashboardWindow(QWidget):

    # Window generated by a SystemBar to help the user
    def __init__(self,parent):
        super(DashboardWindow,self).__init__(parent = parent)

        self.systemBar = SystemBar(parent=self)
        self.menuBar = MenuBar(parent=self)
        
        self.monitoringMenu = QGroupBox(self)
        self.monitoringMenuLayout = QGridLayout()
        self.monitoringMenu.setLayout(self.monitoringMenuLayout)
        self.monitoringMenu.setGeometry(180, 35, 1260, 660)
        
        self.monitoringMenu.setStyleSheet(
            "border:3px solid black;background-color:rgba(0,0,0,0.6)")
        self.initUIContent()
        self.show()

    def initUIContent(self):

        self.crawlingPanel = QGroupBox(parent=self)
        self.crawlingPanelLayout = QGridLayout()
        self.crawlingPanel.setLayout(self.crawlingPanelLayout)
        self.crawlingPanel.setGeometry(200,50,400,300)
        self.crawlingPanel.setStyleSheet("QLabel{color : white; background-color:rgba(0,0,0,0);} QGroupBox{background-color:rgba(0,0,0,0.4); border: none}")

        self.crawlingPanelDescription = QLabel("Vue Rapide : Récupération")
        self.crawlingPanelLayout.addWidget(self.crawlingPanelDescription)
        
        

        self.crawlingPanelFoundRaces = QLabel("Courses trouvées : "+ str(len(self.parent().racesLinks)) )
        self.crawlingPanelLayout.addWidget(self.crawlingPanelFoundRaces)

        self.crawlingPanelFetchedRaces = QLabel("Courses récupérées : " + str(len(self.parent().racesDone)) +" sur "+ str(len(self.parent().racesLinks)) )
        self.crawlingPanelLayout.addWidget(self.crawlingPanelFetchedRaces)
        
        self.monitoringPanel = QGroupBox(parent=self)
        self.monitoringPanelLayout = QGridLayout()
        self.monitoringPanel.setLayout(self.monitoringPanelLayout)
        self.monitoringPanel.setStyleSheet("QLabel{color : white;background-color:rgba(0,0,0,0);} QGroupBox{background-color:rgba(0,0,0,0.4); border : none} ")
        self.monitoringPanel.setGeometry(700,50,400,300)



        self.monitoringPanelDescription = QLabel("Vue Rapide : Surveillance")
        self.monitoringPanelLayout.addWidget(self.monitoringPanelDescription)
        for event in self.parent().eventCache:
  
            self.monitoringPanelLayout.addWidget(QLabel("Course : "+ event[0]+" Participant : "+event[1]+" Variation de cote "+event[2]+" à "+event[3]))

