from Content.Front_End.Widgets.MonitoringScrollArea import MonitoringScrollArea
from PyQt5.QtCore import Qt
from Content.Front_End.Widgets.MonitoringQLabel import MonitoringQLabel
from Content.Front_End.Widgets.MenuBar import MenuBar
from Content.Front_End.Widgets.SystemBar import SystemBar
from PyQt5.QtWidgets import QListWidget, QScrollArea, QScrollBar, QVBoxLayout, QWidget, QGridLayout, QGroupBox, QPushButton, QLabel


class MonitoringWindow(QWidget):

    # Window generated by a SystemBar to help the user
    def __init__(self,parent=None):
        super(MonitoringWindow,self).__init__(parent=parent)

        self.systemBar = SystemBar(parent=self)
        self.menuBar = MenuBar(parent=self)
        self.monitoringMenu = QGroupBox(self)
        self.monitoringMenuLayout = QGridLayout()
        self.monitoringMenu.setLayout(self.monitoringMenuLayout)
        self.monitoringMenu.setGeometry(180, 35, 1100, 690)
        
        self.monitoringMenu.setStyleSheet(
            "QGroupBox {border:3px solid black;background-color:rgba(0,0,0,0.6)}")

        self.setStyleSheet("QLabel{color:white;background-color:rgba(0,0,0,0)} QPushButton{color:white;background-color:rgba(0,0,0,0)}")
        self.initUIContent()
        self.show()

    def initUIContent(self):
        self.currentEventDecriptionLabel = QLabel("Liste des évènements notables durant la surveillance")
        self.monitoringMenuLayout.addWidget(self.currentEventDecriptionLabel,0,0,1,1)
        self.currentEventDecriptionLabel.setStyleSheet("color:white;")

        self.backButton = QPushButton("Démarrer la surveillance des cotes")
        self.backButton.clicked.connect(
           lambda: self.nativeParentWidget().startDashboardWindow())
        self.monitoringMenuLayout.addWidget(self.backButton,7,4,1,1)

        self.monitoringScrollArea = MonitoringScrollArea(parent=self)

        self.monitoringMenuLayout.addWidget(self.monitoringScrollArea,1,0,6,6)

